/**
 * Exercise library. Ported from `ExerciseLibraryItem.swift`, `ExerciseLibraryService.swift`
 * and `FreeExerciseDBLoader.swift`. The catalog is the same FreeExerciseDB corpus the native
 * apps bundle, regenerated by `scripts/build-exercise-catalog.mjs`; animation frames load
 * from the workout-vector CDN exactly like the store builds (`WorkoutFrameStore.swift`).
 */

import catalogData from './exerciseCatalog.json';
import instructionsData from './exerciseInstructions.json';

export interface ExerciseLibraryItem {
  id: string;
  name: string;
  level: string;
  force: string;
  mechanic: string;
  category: string;
  equipment: string;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  /** Number of CDN frames (0 when the exercise has no vector animation). */
  frameCount: number;
  representativeFrameIndex: number;
  /** Per-frame content digests from the shared manifest ('' where unknown); the CDN cache key. */
  maleFrameDigests: readonly string[];
  femaleFrameDigests: readonly string[];
  /** Lower-cased haystack, precomputed so filtering does not rebuild it per keystroke. */
  searchableText: string;
}

type CatalogTuple = [string, string, string, string, string, string, string, string[], string[], number, number, string, string];

export const UNSPECIFIED = 'Unspecified';

/** `ExerciseLibraryItem.metadataTitle` — Title Case, hyphen-aware, "Unspecified" when blank. */
export function metadataTitle(value: string | null | undefined): string {
  const trimmed = value?.trim() ?? '';
  if (!trimmed) return UNSPECIFIED;
  return trimmed
    .split(' ')
    .map((word) =>
      word
        .split('-')
        .map((segment) => (segment ? segment.charAt(0).toUpperCase() + segment.slice(1).toLowerCase() : ''))
        .join('-'),
    )
    .join(' ');
}

function metadataTitles(values: readonly string[]): string[] {
  return values.map(metadataTitle).filter((v) => v !== UNSPECIFIED);
}

export function makeExerciseLibraryItem(input: {
  id: string;
  name: string;
  level?: string | null;
  force?: string | null;
  mechanic?: string | null;
  category?: string | null;
  equipment?: string | null;
  primaryMuscles?: readonly string[];
  secondaryMuscles?: readonly string[];
  frameCount?: number;
  representativeFrameIndex?: number;
  maleFrameDigests?: readonly string[];
  femaleFrameDigests?: readonly string[];
}): ExerciseLibraryItem {
  const item = {
    id: input.id,
    name: input.name.trim(),
    level: metadataTitle(input.level),
    force: metadataTitle(input.force),
    mechanic: metadataTitle(input.mechanic),
    category: metadataTitle(input.category),
    equipment: metadataTitle(input.equipment),
    primaryMuscles: metadataTitles(input.primaryMuscles ?? []),
    secondaryMuscles: metadataTitles(input.secondaryMuscles ?? []),
    frameCount: input.frameCount ?? 0,
    representativeFrameIndex: input.representativeFrameIndex ?? 0,
    maleFrameDigests: input.maleFrameDigests ?? [],
    femaleFrameDigests: input.femaleFrameDigests ?? [],
  };
  return {
    ...item,
    searchableText: [item.name, item.level, item.force, item.mechanic, item.category, item.equipment, item.primaryMuscles.join(' '), item.secondaryMuscles.join(' ')]
      .join(' ')
      .toLowerCase(),
  };
}

let cachedCatalog: ExerciseLibraryItem[] | undefined;

/** The bundled catalog, sorted by name (`FreeExerciseDBLoader.load`). Parsed once. */
export function exerciseCatalog(): ExerciseLibraryItem[] {
  if (!cachedCatalog) {
    cachedCatalog = (catalogData as CatalogTuple[]).map(([id, name, level, force, mechanic, equipment, category, primary, secondary, frameCount, representative, maleDigests, femaleDigests]) =>
      makeExerciseLibraryItem({
        id,
        name,
        level,
        force,
        mechanic,
        equipment,
        category,
        primaryMuscles: primary,
        secondaryMuscles: secondary,
        frameCount,
        representativeFrameIndex: representative,
        maleFrameDigests: maleDigests ? maleDigests.split(',') : [],
        femaleFrameDigests: femaleDigests ? femaleDigests.split(',') : [],
      }),
    );
  }
  return cachedCatalog;
}

export function exerciseById(id: string): ExerciseLibraryItem | undefined {
  return exerciseCatalog().find((item) => item.id === id);
}

export function primaryMusclesTitle(item: ExerciseLibraryItem): string {
  return item.primaryMuscles.length === 0 ? UNSPECIFIED : item.primaryMuscles.join(', ');
}

export function secondaryMusclesTitle(item: ExerciseLibraryItem): string {
  return item.secondaryMuscles.length === 0 ? 'None' : item.secondaryMuscles.join(', ');
}

/** `databaseMetadataSummary` — "Strength - Push - Compound". */
export function metadataSummary(item: ExerciseLibraryItem): string {
  const parts = [item.category, item.force, item.mechanic].filter((p) => p !== UNSPECIFIED);
  return parts.length > 0 ? parts.join(' - ') : 'Database metadata';
}

// MARK: - Frames (CDN)

export const WORKOUT_FRAME_BASE_URL = 'https://assets.fud-ai.app/workout-vectors/v2';

export type FrameSex = 'male' | 'female';

export function frameName(item: Pick<ExerciseLibraryItem, 'id'>, sex: FrameSex, index: number): string {
  return `${item.id}_${sex}_v2_${index}`;
}

/** `WorkoutFrameStore.normalizedDigest` — 8…64 lower-case hex characters, otherwise no digest. */
export function normalizedFrameDigest(digest: string | undefined): string | undefined {
  const value = digest?.trim().toLowerCase();
  return value && value.length >= 8 && value.length <= 64 && /^[0-9a-f]+$/.test(value) ? value : undefined;
}

/**
 * `WorkoutFrameStore.remoteURL`: the frame PNG on the CDN with the manifest digest as a `v`
 * query item, so a frame replaced under the same name is fetched again instead of served
 * from an HTTP or image cache.
 */
export function frameURL(item: Pick<ExerciseLibraryItem, 'id' | 'frameCount'> & Partial<Pick<ExerciseLibraryItem, 'maleFrameDigests' | 'femaleFrameDigests'>>, sex: FrameSex, index: number): string | undefined {
  if (item.frameCount <= 0 || index < 0 || index >= item.frameCount) return undefined;
  const digests = sex === 'female' ? item.femaleFrameDigests : item.maleFrameDigests;
  const digest = normalizedFrameDigest(digests?.[index]);
  return `${WORKOUT_FRAME_BASE_URL}/${frameName(item, sex, index)}.png${digest ? `?v=${digest}` : ''}`;
}

export function representativeFrameURL(item: ExerciseLibraryItem, sex: FrameSex): string | undefined {
  return frameURL(item, sex, item.representativeFrameIndex);
}

// MARK: - Filtering & sorting

export const exerciseLibrarySorts = ['name', 'level', 'primaryMuscles', 'category', 'equipment'] as const;
export type ExerciseLibrarySort = (typeof exerciseLibrarySorts)[number];

export function exerciseLibrarySortTitle(sort: ExerciseLibrarySort): string {
  switch (sort) {
    case 'name':
      return 'Name';
    case 'level':
      return 'Level';
    case 'primaryMuscles':
      return 'Primary';
    case 'category':
      return 'Category';
    case 'equipment':
      return 'Equipment';
  }
}

export interface ExerciseFilter {
  searchText: string;
  levels: readonly string[];
  equipment: readonly string[];
  primaryMuscles: readonly string[];
  categories: readonly string[];
  sort: ExerciseLibrarySort;
}

export const emptyExerciseFilter: ExerciseFilter = { searchText: '', levels: [], equipment: [], primaryMuscles: [], categories: [], sort: 'name' };

export function hasActiveFilters(filter: ExerciseFilter): boolean {
  return (
    filter.searchText.trim().length > 0 ||
    filter.levels.length > 0 ||
    filter.equipment.length > 0 ||
    filter.primaryMuscles.length > 0 ||
    filter.categories.length > 0 ||
    filter.sort !== 'name'
  );
}

const levelOrder: Record<string, number> = { Beginner: 0, Intermediate: 1, Expert: 2 };

function distinct(values: readonly string[]): string[] {
  return [...new Set(values.filter((v) => v !== UNSPECIFIED))].sort((a, b) => a.localeCompare(b));
}

export interface ExerciseFilterOptions {
  levels: string[];
  equipment: string[];
  primaryMuscles: string[];
  categories: string[];
}

/** `ExerciseLibraryService.available*` — option lists derived from the catalog itself. */
export function exerciseFilterOptions(items: readonly ExerciseLibraryItem[]): ExerciseFilterOptions {
  return {
    levels: distinct(items.map((i) => i.level)).sort((a, b) => (levelOrder[a] ?? 9) - (levelOrder[b] ?? 9)),
    equipment: distinct(items.map((i) => i.equipment)),
    primaryMuscles: distinct(items.flatMap((i) => i.primaryMuscles)),
    categories: distinct(items.map((i) => i.category)),
  };
}

/** Every search token must appear somewhere in the haystack; filter sets are OR within, AND across. */
export function filterExercises(items: readonly ExerciseLibraryItem[], filter: ExerciseFilter): ExerciseLibraryItem[] {
  const tokens = filter.searchText.toLowerCase().split(/\s+/).filter(Boolean);
  const matches = items.filter((item) => {
    if (tokens.length > 0 && !tokens.every((token) => item.searchableText.includes(token))) return false;
    if (filter.levels.length > 0 && !filter.levels.includes(item.level)) return false;
    if (filter.equipment.length > 0 && !filter.equipment.includes(item.equipment)) return false;
    if (filter.categories.length > 0 && !filter.categories.includes(item.category)) return false;
    if (filter.primaryMuscles.length > 0 && !item.primaryMuscles.some((m) => filter.primaryMuscles.includes(m))) return false;
    return true;
  });
  return sortExercises(matches, filter.sort);
}

export function sortExercises(items: readonly ExerciseLibraryItem[], sort: ExerciseLibrarySort): ExerciseLibraryItem[] {
  const byName = (a: ExerciseLibraryItem, b: ExerciseLibraryItem) => a.name.localeCompare(b.name, undefined, { sensitivity: 'base' });
  const key = (item: ExerciseLibraryItem): string => {
    switch (sort) {
      case 'name':
        return '';
      case 'level':
        return String(levelOrder[item.level] ?? 9);
      case 'primaryMuscles':
        return item.primaryMuscles[0] ?? '~';
      case 'category':
        return item.category;
      case 'equipment':
        return item.equipment;
    }
  };
  return [...items].sort((a, b) => key(a).localeCompare(key(b)) || byName(a, b));
}

// MARK: - Instructions

/** Instructions are a separate module so the catalog tuple file stays small and reviewable. */
export function exerciseInstructions(id: string): string[] {
  return (instructionsData as Record<string, string[]>)[id] ?? [];
}
